---
title: 'Cancer Risk from Air Toxins '
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rgdal)
library(sf)
library(leaflet)
library(RColorBrewer)
library(flextable)
library(htmltools)
library(htmlwidgets)
library(leafpop)
library(tigris)

options(tigris_use_cache = TRUE)

or_tracts <- tracts(state = "41", year = 2019)

## read in the cancer risk data for the state and county-level risk
at_st <- read.csv("results/or_air_toxics_ambient_cancer_risk_counties.csv", stringsAsFactors = FALSE)
at_st <- at_st %>% select("County", "Tract", "Pollutant.Name", risk = "Total.Cancer.Risk..per.million.")
st_at_ris <- at_st %>% group_by(County) %>% summarize(tot_ris = sum(risk, na.rm = TRUE)) %>% filter(County == "Entire State")
st_form_ris <- at_st %>% filter(County == "Entire State") %>% filter(Pollutant.Name == "FORMALDEHYDE") %>% select(risk)
st_dpm_ris <- at_st %>% filter(County == "Entire State") %>% filter(Pollutant.Name == "DIESEL PM") %>% select(risk)

## read in the tract-level info
or_ris_tracts <- read.csv("results/or_air_toxics_ambient_cancer_risk_tracts.csv", stringsAsFactors = FALSE)
or_tot_can <- or_ris_tracts %>% group_by(Tract) %>% 
                                  summarize(County = first(County),
                                            pop10 = first(Population),
                                            cancer_ris = sum(Total.Cancer.Risk..per.million., na.rm = TRUE))
or_form_can <- or_ris_tracts %>% filter(Pollutant.Name == "FORMALDEHYDE") %>% 
                                 select(Tract,form_ris = Total.Cancer.Risk..per.million.)
or_dpm_can <- or_ris_tracts %>% filter(Pollutant.Name == "DIESEL PM") %>% 
                                 select(Tract,dpm_ris = Total.Cancer.Risk..per.million.)
or_tot_can <- merge(or_tot_can, or_form_can, by = "Tract", all = TRUE )
or_tot_can <- merge(or_tot_can, or_dpm_can, by = "Tract", all = TRUE )
rm(or_form_can, or_dpm_can)

or_ris_tracts$chr_tract <- as.character(or_ris_tracts$Tract)
or_tot <- merge(or_tracts, or_tot_can, by.x = "GEOID", by.y = "Tract")


## add path for pre-generated graphs for each tract
or_tot$at_img <- paste0("images/totp_", or_tot$GEOID, ".png" )
or_tot$form_img <- paste0("images/form_", or_tot$GEOID, ".png" )
or_tot$dpm_img <- paste0("images/dpm_", or_tot$GEOID, ".png" )

#create pop-ups, one for each layer in the map
pop_title <- paste0("<u>Tract ", or_tot$GEOID, ", ", or_tot$County, " County </u> <br/> Population (2010) ", or_tot$pop10, "<br>" )
or_tot$lab = paste0( or_tot$GEOID, ", ", or_tot$County, " County")
or_tot$popn = 
    paste(pop_title, 
    "<b>Tract cancer risk :</b> ", as.character(round(or_tot$cancer_ris)), " per million",                              
    "<br><b>State-wide cancer risk :</b> ", as.character(round(st_at_ris$tot_ris)), " per million <br><br><br>")


or_tot$popf = 
    paste(pop_title, 
    "<b>Tract cancer risk from formaldehyde :</b> ", as.character(round(or_tot$form_ris)), " per million",     
    "<br><b>State-wide cancer risk from formaldehyde:</b>", as.character(round(st_form_ris)), " per million <br><br><br>")


or_tot$popd = 
    paste(pop_title, 
    "<b>Tract cancer risk from diesel pm :</b> ", as.character(round(or_tot$dpm_ris)), " per million", 
    "<br><b>State-wide cancer risk from diesel pm:</b> ", as.character(round(st_dpm_ris)),  " per million <br><br><br>")

## assign color palettes to the choropleth maps
npal <- colorNumeric(palette = "YlOrRd", domain = or_tot$cancer_ris)
fpal <- colorNumeric(palette = "BuPu", domain = or_tot$form_ris)
dpal <- colorNumeric(palette = "Greys", domain = or_tot$dpm_ris)

## remove any existing map....useful for the debugging phase
rm(m)

## create the leaflet map
m = leaflet(height = 800) %>%      
  addProviderTiles(providers$Esri.WorldGrayCanvas, group = "ESRI World Gray") %>% 
  addProviderTiles(providers$Esri.WorldStreetMap, group = "ESRI World Street") %>%
  setView(-121, 44.6, 7) %>% 
  addPolygons(data=or_tot, group = "45 air toxins", color = "#cccccc", weight = 0.2, smoothFactor = 0.5,
              opacity = 0.4, fillOpacity = 0.7,
              fillColor = ~npal(cancer_ris),
              label = ~lab,
              popup = ~popn, 
              highlightOptions = highlightOptions(color = "#aaaaaa", weight = 1, bringToFront = TRUE)) %>%
  addPopupImages(image = or_tot$at_img, group = "45 air toxins", height = 500 ) %>%
  addLegend(group = "45 air toxins", "bottomleft", title = "cancer risk <br>(# per million)", pal = npal, values = or_tot$cancer_ris) %>%
  
  addPolygons(data=or_tot, group = "formaldehyde", color = "#cccccc", weight = 0.2, smoothFactor = 0.5,
              opacity = 0.4, fillOpacity = 0.7,
              fillColor = ~fpal(form_ris),
              label = ~lab,
              popup = ~popf, 
              highlightOptions = highlightOptions(color = "#aaaaaa", weight = 1, bringToFront = TRUE)) %>%
  addPopupImages(image = or_tot$form_img, group = "formaldehyde", width = 300 ) %>%
  addLegend(group = "formaldehyde", "bottomleft", title = "cancer risk <br>(# per million)", pal = fpal, values = or_tot$form_ris) %>%
  
  addPolygons(data=or_tot, group = "diesel pm", color = "#cccccc", weight = 0.2, smoothFactor = 0.5,
              opacity = 0.4, fillOpacity = 0.8,
              fillColor = ~dpal(dpm_ris),
              label = ~lab,
              popup = ~popd, 
              highlightOptions = highlightOptions(color = "#aaaaaa", weight = 1, bringToFront = TRUE)) %>%
  addPopupImages(image = or_tot$dpm_img, group = "diesel pm", width = 300 ) %>%
  addLegend(group = "diesel pm", "bottomleft", title = "cancer risk <br>(# per million)", pal = dpal, values = or_tot$dpm_ris) %>%

  addLayersControl(
        baseGroups = c("ESRI World Street", "ESRI World Gray" ),
        overlayGroups = c("45 air toxins", "formaldehyde", "diesel pm"),
        options = layersControlOptions(collapsed = TRUE)) %>%
  hideGroup("formaldehyde") %>%
  hideGroup("diesel pm")


```
Based on NATA 2014 ambient air concetrations
<br><br>
```{r map, out.width = '100%', echo = FALSE }
## display the map
m

```


 



